ITHootUniversity/ViewModels/CRUDUserViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace ITHootUniversity.ViewModels
{
    public class CRUDUserViewModel
    {
        [Required]
        public string UserName { get; set; }

        public string Password { get; set; }

        public string Role { get; set; }
    }
}

ITHootUniversity/ViewModels/CabinetViewModel.cs
namespace ITHootUniversity.ViewModels
{
    public class CabinetViewModel
    {
        public List<UserViewModel> UserViewModels { get; set; }

        public List<LessonViewModel> LessonViewModels { get; set; }

        public List<string> Roles { get; set; }
    }
}

ITHootUniversity/ViewModels/LessonViewModel.cs
namespace ITHootUniversity.ViewModels
{
    public class LessonViewModel
    {
        public string LessonName { get; set; }

        public virtual List<UserViewModel> Users { get; set; }
        public LessonViewModel()
        {
            Users = new List<UserViewModel>();
        }
    }
}

ITHootUniversity/ViewModels/SignInUserViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace ITHootUniversity.ViewModels
{
    public class SignInUserViewModel
    {
        [Required]
        [Display(Name = "UserName")]
        public string UserName { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }
    }
}

ITHootUniversity/ViewModels/UserViewModel.cs
namespace ITHootUniversity.ViewModels
{
    public class UserViewModel
    {
        public string UserName { get; set; }

        public string Role { get; set; }

        public virtual List<LessonViewModel> Lessons { get; set; }
        public UserViewModel()
        {
            Lessons = new List<LessonViewModel>();
        }
    }
}

ITHootUniversity/Controllers/CabinetController.cs
using BusinessLogicLayer.DtoModels;
using BusinessLogicLayer.Services.Implementations;
using BusinessLogicLayer.Services.Interfaces;
using ITHootUniversity.ViewModels;
using ITHootUniversity.WebAppFactories.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ITHootUniversity.Controllers
{
    [Authorize]
    public class CabinetController : Controller
    {
        private readonly IUsersService usersService;
        private readonly ILessonsService lessonsService;
        private readonly IUsersInLessonsService usersInLessonsService;
        private readonly IViewModelToDtoFactory viewModelToDtoFactory;
        private readonly ICabinetViewModelFactory cabinetViewModelService;
        public CabinetController(IUsersService usersService, IViewModelToDtoFactory viewModelToDtoFactory, ICabinetViewModelFactory cabinetViewModelService, ILessonsService lessonsService, IUsersInLessonsService usersInLessonsService)
        {
            this.usersService = usersService;
            this.viewModelToDtoFactory = viewModelToDtoFactory;
            this.cabinetViewModelService = cabinetViewModelService;
            this.lessonsService = lessonsService;
            this.usersInLessonsService = usersInLessonsService;
        }

        public async Task<IActionResult> Index()
        {
            return View(await cabinetViewModelService.CreateAndFillCabinetViewModel());
        }

        [HttpPost]
        public async Task<JsonResult> GetJsonCabinetViewModel()
        {
            return new JsonResult(await cabinetViewModelService.CreateAndFillCabinetViewModel());
        }

        [HttpPost]
        public async Task<JsonResult> CreateOrUpdateUser(CRUDUserViewModel user)
        {
           return new JsonResult(await usersService.CreateOrUpdateUser(viewModelToDtoFactory.TransformCRUDUserViewModelToDtoUserModel(user)));
        }

        [HttpPost]
        public async Task<JsonResult> DeleteUser(string userName)
        {
            return new JsonResult(await usersService.DeleteUser(userName));
        }

        [HttpPost]
        public async Task<JsonResult> CreateLesson(string lessonName, string userName)
        {
            return new JsonResult(await lessonsService.CreateLesson(lessonName, userName));
        }

        [HttpPost]
        public async Task<JsonResult> DeleteLesson(string lessonName)
        {
            return new JsonResult(await lessonsService.DeleteLesson(lessonName));
        }

        [HttpPost]
        public async Task<JsonResult> AddUserToLesson(string lessonName, string userName)
        {
            return new JsonResult(await usersInLessonsService.AddUserToLesson(lessonName, userName));
        }

        [HttpPost]
        public async Task<JsonResult> DelUserFromLesson(string lessonName, string userName)
        {
            return new JsonResult(await usersInLessonsService.DelUserFromLesson(lessonName, userName));
        }

        [HttpPost]
        public async Task<JsonResult> JoinToLesson(string lessonName)
        {
            return new JsonResult(await usersInLessonsService.JoinToLesson(lessonName, User.Identity.Name));
        }

        [HttpPost]
        public async Task<JsonResult> LeftFromLesson(string lessonName)
        {
            return new JsonResult(await usersInLessonsService.LeftFromLesson(lessonName, User.Identity.Name));
        }
    }
}

ITHootUniversity/Controllers/HomeController.cs
using BusinessLogicLayer.Services.Interfaces;
using DataAccessLayer.DbContexts;
using DataAccessLayer.Models;
using ITHootUniversity.ViewModels;
using ITHootUniversity.WebAppFactories.Interfaces;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;

namespace ITHootUniversity.Controllers
{
    public class HomeController : Controller
    {

        private readonly SignInManager<UserModel> signInManager;
        private readonly RoleManager<IdentityRole> roleManager;

        private readonly IUsersService usersService;
        private readonly IViewModelToDtoFactory viewModelToDtoFactory;


        private readonly IResultBuilderService resultBuilderService;
        public HomeController(SignInManager<UserModel> signInManager, RoleManager<IdentityRole> roleManager, IResultBuilderService resultBuilderService, IUsersService usersService, IViewModelToDtoFactory viewModelToDtoFactory)
        {
            this.signInManager = signInManager;
            this.resultBuilderService = resultBuilderService;
            this.usersService = usersService;
            this.viewModelToDtoFactory = viewModelToDtoFactory;
            this.roleManager = roleManager;

        }

        public async  Task<IActionResult> Index()
        {
            //await roleManager.CreateAsync(new IdentityRole("Teacher"));
            //await usersService.CreateOrUpdateUser(viewModelToDtoFactory.TransformCRUDUserViewModelToDtoUserModel(new CRUDUserViewModel { Password ="2288228Qq]", Role = "Admin", UserName="DOKERcom"}));
            return View();
        }

        [HttpPost]
        public async Task<JsonResult> SignIn(SignInUserViewModel model)
        {
            if (ModelState.IsValid) 
            {
                var result = await signInManager.PasswordSignInAsync(model.UserName, model.Password, false, false);
                if (result.Succeeded)
                {
                    return new JsonResult(resultBuilderService.ToModelForJsonResult("ok", ""));
                }
                else
                {
                    return new JsonResult(resultBuilderService.ToModelForJsonResult("", $"Incorrect login and/or password"));
                } 
            }

            return Json(new { ResultAction = "", ResultMessage = $"The parameters obtained did not pass validation" });
        }

        public async Task<IActionResult> Logout()
        {
            await signInManager.SignOutAsync();

            return RedirectToAction("Index", "Home");
        }
    }
}

ITHootUniversity/Views/Home/Index.cshtml
@model SignInUserViewModel
@{
    @if(User.Identity.IsAuthenticated)
    {
        <div class="form_block">
            <div class="form">
                <div class="name_block">
                    <label class="fs_1_5vw">Hello, @(User.Identity.Name)! You already in account!</label>
                </div>
            </div>
        </div>
    }
    else
    {
    <div class="form_block">
        <div class="form">
            <div class="name_block">
                <label class="fs_1_5vw">SIGN IN FORM</label>
            </div>
            <div class="input_block">
                <label for="Login">Login:</label>
                <input asp-for="UserName" id="Login" maxlength="25" type="text" name="Login">
                <span asp-validation-for="UserName"></span>
            </div>
            <div class="input_block">
                <label for="Password">Password:</label>
                <input asp-for="Password" id="Password" maxlength="25" type="text" name="Password">
                <span asp-validation-for="Password"></span>
            </div>
            <div class="submit_button">
                <input type="submit" onclick="AuthFunc(document.getElementById('Login').value, document.getElementById('Password').value)" value="SIGN IN">
            </div>
        </div>
    </div>
    }
}
<script type="text/javascript" src="js/homeindex.js"></script>

ITHootUniversity/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>University</title>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="css/dropstyles.css">
    <link rel="stylesheet" type="text/css" href="css/dizel.css">
    <link rel="stylesheet" type="text/css" href="css/index.css">
</head>
<body>
    <div class="wrapper">
        <div class="header">
            <div class="header_small">
                <div class="header_menu">
                    @{
                        @if(User.Identity.IsAuthenticated)
                        {
                             <a asp-area="" asp-controller="Cabinet" asp-action="Index"><div class="menu_button"><p class="fs_1vw">@(User.Identity.Name)</p></div></a>
                             <a asp-area="" asp-controller="Home" asp-action="Logout"><div class="menu_button"><p class="fs_1vw">LOGOUT</p></div></a>
                        }
                        else
                        {
                             <a asp-area="" asp-controller="Home" asp-action="Index"><div class="menu_button"><p class="fs_1vw">SIGN IN</p></div></a>
                        }
                    }
                </div>
            </div>
            <div class="header_big">
                <p class="fs_2_5vw">UNIVERSITY</p>
            </div>
        </div>
        <div class="mainbody">
            @RenderBody()
        </div>
        <div class="footer">
            <div class="footer_name">
                <p class="fs_1vw">2022 ITHOOT DOKERcom</p>
            </div>
        </div>
    </div>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>